format = """
$directory\
$git_branch\
$git_status\
$python\
$character"""

[python]
symbol = 'îœ¼ '

# ~/.config/starship.toml

[git_branch]
symbol = "ó°˜¬ "

[git_status]
staged = "[+](green)"
untracked = "[?](red)"
modified = "[*](yellow)"
# conflicted = 'ğŸ³'
# ahead = 'ğŸğŸ’¨'
# behind = 'ğŸ˜°'
# diverged = 'ğŸ˜µ'
# up_to_date = 'âœ“'
# untracked = 'ğŸ¤·'
# stashed = 'ğŸ“¦'
# modified = 'ğŸ“'
# staged = '[++\($count\)](green)'
# renamed = 'ğŸ‘…'
# deleted = 'ğŸ—‘'
#
# staged= '[ï“ \($count\)](green)'
# conflicted= "ó°•š "
# untracked= "ó±€¶ "
# modified= "ï‘™ "
# stashed= "îª˜ "
# up_to_date= "ï˜ "
   # insertions: "ï‘— "
   # deletions: "ï‘˜ "

#[directory]
## style = "blue"
#
#[character]
#success_symbol = "[â¯](purple)"
#error_symbol = "[â¯](red)"
#vimcmd_symbol = "[â®](green)"
#
#[package]
#disabled = true
#
#[username]
#disabled = true
#
#[hostname]
#disabled = true
#
#[aws]
#disabled = true
#
#[docker_context]
#disabled = true
#
#[git_branch]
#disabled = true
#
#[git_commit]
#disabled = true
#
#[git_state]
#disabled = true
#
#[git_metrics]
#disabled = true
#
#[git_status]
#disabled = true
#
#[battery]
#disabled = true
